SELECT
    Name1,
    Email1,
    Name2,
    Email2,
    Name3,
    Email3,
    Name4,
    Email4,
    SiteName,
    SurveyDate,
    COALESCE(StartTime, '') AS StartTime,
    GroupCode,
    Address,
    City,
    County,
    COALESCE(Latitude, '') AS Latitude,
    COALESCE(Longitude, '') AS Longitude,
    SoundImpactsId,
    COALESCE(RainfallToday, '') AS RainfallToday,
    COALESCE(RainfallYesterday, '') AS RainfallYesterday,
    COALESCE(RainfallTwoDaysAgo, '') AS RainfallTwoDaysAgo,
    SiteTypeId,
    SiteAgeId,
    AgeSourceId,
    AgeSourceDescription,
    COALESCE(GROUP_CONCAT(formwatersource.WaterSourceId), '') AS WaterSources,
    Overflow1Id,
    Overflow2Id,
    Overflow3Id,
    Inflow1BlockagePercentId,
    Inflow2BlockagePercentId,
    Inflow3BlockagePercentId,
    SheetFlowBlockagePercentId,
    Overflow1BlockagePercentId,
    Overflow2BlockagePercentId,
    Overflow3BlockagePercentId,
    Inflow1BlockageTypeId,
    Inflow2BlockageTypeId,
    Inflow3BlockageTypeId,
    SheetFlowBlockageTypeId,
    Overflow1BlockageTypeId,
    Overflow2BlockageTypeId,
    Overflow3BlockageTypeId,
    Zone1ErosionId,
    Zone2ErosionId,
    Zone3ErosionId,
    HydrologyConcerns,
    COALESCE(Zone1Length, '') AS Zone1Length,
    COALESCE(Zone1Length / 3.0, '') AS SectionLength,
    COALESCE(sectioninfo1A.StandingWaterDepth, '') AS StandingWaterDepth1A,
    sectioninfo1A.SiltationDepthId AS SiltationDepth1A,
    sectioninfo1A.LinerPresent AS LinerPresent1A,
    COALESCE(sectioninfo1A.LinerDepth, '') AS LinerDepth1A,
    sectioninfo1A.FilterFabricPresent AS FilterFabricPresent1A,
    COALESCE(sectioninfo1A.FilterFabricDepth, '') AS FilterFabricDepth1A,
    COALESCE(sectioninfo1A.NativeSoilDepth, '') AS NativeSoilDepth1A,
    COALESCE(sectioninfo1A.CompactedSurfaceSoils, '') AS CompactedSurfaceSoils1A,
    sectioninfo1A.RainGardenMixSoilTextureId AS GardenMixSoilTexture1A,
    sectioninfo1A.NativeTextureId AS NativeSoilTexture1A,
    COALESCE(sectioninfo1B.StandingWaterDepth, '') AS StandingWaterDepth1B,
    sectioninfo1B.SiltationDepthId AS SiltationDepth1B,
    sectioninfo1B.LinerPresent AS LinerPresent1B,
    COALESCE(sectioninfo1B.LinerDepth, '') AS LinerDepth1B,
    sectioninfo1B.FilterFabricPresent AS FilterFabricPresent1B,
    COALESCE(sectioninfo1B.FilterFabricDepth, '') AS FilterFabricDepth1B,
    COALESCE(sectioninfo1B.NativeSoilDepth, '') AS NativeSoilDepth1B,
    COALESCE(sectioninfo1B.CompactedSurfaceSoils, '') AS CompactedSurfaceSoils1B,
    sectioninfo1B.RainGardenMixSoilTextureId AS GardenMixSoilTexture1B,
    sectioninfo1B.NativeTextureId AS NativeSoilTexture1B,
    COALESCE(sectioninfo1C.StandingWaterDepth, '') AS StandingWaterDepth1C,
    sectioninfo1C.SiltationDepthId AS SiltationDepth1C,
    sectioninfo1C.LinerPresent AS LinerPresent1C,
    COALESCE(sectioninfo1C.LinerDepth, '') AS LinerDepth1C,
    sectioninfo1C.FilterFabricPresent AS FilterFabricPresent1C,
    COALESCE(sectioninfo1C.FilterFabricDepth, '') AS FilterFabricDepth1C,
    COALESCE(sectioninfo1C.NativeSoilDepth, '') AS NativeSoilDepth1C,
    COALESCE(sectioninfo1C.CompactedSurfaceSoils, '') AS CompactedSurfaceSoils1C,
    sectioninfo1C.RainGardenMixSoilTextureId AS GardenMixSoilTexture1C,
    sectioninfo1C.NativeTextureId AS NativeSoilTexture1C,
    SubstrateObservations,
    MulchType1AId,
    MulchType1BId,
    MulchType1CId,
    MulchType2Id,
    MulchType3Id,
    MulchDepth1AId,
    MulchDepth1BId,
    MulchDepth1CId,
    MulchDepth2Id,
    MulchDepth3Id,
    zoneinfo1.MulchCoverageId AS MulchCoverage1,
  	zoneinfo1.BareGroundCoverageId AS GroundCoverage1,
  	zoneinfo1.PeaGravelCoverageId AS GravelCoverage1,
  	zoneinfo1.DrainRockCoverageId AS DrainRockCoverage1,
  	zoneinfo1.Rock2To12InchCoverageId AS LowRockCoverage1,
  	zoneinfo1.RockGreaterThan12InchCoverageId AS HighRockCoverage1,
  	zoneinfo1.AllVegetationCoverageId AS AllVegetationCoverage1,
  	zoneinfo1.ProblemPlantsCoverageId AS ProblemPlantCoverage1,
  	zoneinfo1.NonTargetWeedCoverageId AS WeedCoverage1,
  	zoneinfo1.DeciduousCoverageId AS DeciduousCoverage1,
  	zoneinfo1.EvergreenCoverageId AS EvergreenCoverage1,
  	zoneinfo1.HerbaceousCoverageId AS HerbaceousCoverage1,
  	zoneinfo1.GroundCoverCoverageId AS GroundCoverCoverage1,
  	zoneinfo1.ProblemPlantsVigorId AS PlantVigor1,
  	zoneinfo1.NonTargetWeedVigorId AS WeedVigor1,
  	zoneinfo1.DeciduousVigorId AS DeciduousVigor1,
  	zoneinfo1.EvergreenVigorId AS EvergreenVigor1,
  	zoneinfo1.HerbaceousVigorId AS HerbaceousVigor1,
  	zoneinfo1.GroundCoverVigorId AS GroundVigor1,
    zoneinfo2.MulchCoverageId AS MulchCoverage2,
  	zoneinfo2.BareGroundCoverageId AS GroundCoverage2,
  	zoneinfo2.PeaGravelCoverageId AS GravelCoverage2,
  	zoneinfo2.DrainRockCoverageId AS DrainRockCoverage2,
  	zoneinfo2.Rock2To12InchCoverageId AS LowRockCoverage2,
  	zoneinfo2.RockGreaterThan12InchCoverageId AS HighRockCoverage2,
  	zoneinfo2.AllVegetationCoverageId AS AllVegetationCoverage2,
  	zoneinfo2.ProblemPlantsCoverageId AS ProblemPlantCoverage2,
  	zoneinfo2.NonTargetWeedCoverageId AS WeedCoverage2,
  	zoneinfo2.DeciduousCoverageId AS DeciduousCoverage2,
  	zoneinfo2.EvergreenCoverageId AS EvergreenCoverage2,
  	zoneinfo2.HerbaceousCoverageId AS HerbaceousCoverage2,
  	zoneinfo2.GroundCoverCoverageId AS GroundCoverCoverage2,
  	zoneinfo2.ProblemPlantsVigorId AS PlantVigor2,
  	zoneinfo2.NonTargetWeedVigorId AS WeedVigor2,
  	zoneinfo2.DeciduousVigorId AS DeciduousVigor2,
  	zoneinfo2.EvergreenVigorId AS EvergreenVigor2,
  	zoneinfo2.HerbaceousVigorId AS HerbaceousVigor2,
  	zoneinfo2.GroundCoverVigorId AS GroundVigor2,
    zoneinfo3.MulchCoverageId AS MulchCoverage3,
  	zoneinfo3.BareGroundCoverageId AS GroundCoverage3,
  	zoneinfo3.PeaGravelCoverageId AS GravelCoverage3,
  	zoneinfo3.DrainRockCoverageId AS DrainRockCoverage3,
  	zoneinfo3.Rock2To12InchCoverageId AS LowRockCoverage3,
  	zoneinfo3.RockGreaterThan12InchCoverageId AS HighRockCoverage3,
  	zoneinfo3.AllVegetationCoverageId AS AllVegetationCoverage3,
  	zoneinfo3.ProblemPlantsCoverageId AS ProblemPlantCoverage3,
  	zoneinfo3.NonTargetWeedCoverageId AS WeedCoverage3,
  	zoneinfo3.DeciduousCoverageId AS DeciduousCoverage3,
  	zoneinfo3.EvergreenCoverageId AS EvergreenCoverage3,
  	zoneinfo3.HerbaceousCoverageId AS HerbaceousCoverage3,
  	zoneinfo3.GroundCoverCoverageId AS GroundCoverCoverage3,
  	zoneinfo3.ProblemPlantsVigorId AS PlantVigor3,
  	zoneinfo3.NonTargetWeedVigorId AS WeedVigor3,
  	zoneinfo3.DeciduousVigorId AS DeciduousVigor3,
  	zoneinfo3.EvergreenVigorId AS EvergreenVigor3,
  	zoneinfo3.HerbaceousVigorId AS HerbaceousVigor3,
  	zoneinfo3.GroundCoverVigorId AS GroundVigor3,
    VegetationObservations,
    VisibleToPublicId,
    AestheticallyPleasingId,
    WellMaintainedId,
    COALESCE(EducationalSignage, '') AS EducationalSignage,
    OtherObservations,
    COALESCE(EndTime, '') AS EndTime
FROM
    form
    JOIN sectioninfo AS sectioninfo1A
    	ON form.Section1AInfoId = sectioninfo1A.SectionInfoId
    JOIN sectioninfo AS sectioninfo1B
    	ON form.Section1BInfoId = sectioninfo1B.SectionInfoId
    JOIN sectioninfo AS sectioninfo1C
    	ON form.Section1CInfoId = sectioninfo1C.SectionInfoId
    JOIN zoneinfo AS zoneinfo1
    	ON form.Zone1InfoId = zoneinfo1.ZoneInfoId
    JOIN zoneinfo AS zoneinfo2
    	ON form.Zone2InfoId = zoneinfo2.ZoneInfoId
    JOIN zoneinfo AS zoneinfo3
    	ON form.Zone3InfoId = zoneinfo3.ZoneInfoId
    LEFT JOIN formwatersource
      ON form.FormId = formwatersource.FormId
    GROUP By form.FormId;




